// src/js/constants/action-types.js
export const ADD_DAY_CREATED = "ADD_DAY_CREATED";
export const ADD_DAY_CLOSED = "ADD_DAY_CLOSED";
export const ADD_DAY_VELOCITY_CLOSED = "ADD_DAY_VELOCITY_CLOSED";
export const ADD_DAY_VELOCITY_CREATED = "ADD_DAY_VELOCITY_CREATED";

export const ADD_WEEK_CREATED = "ADD_WEEK_CREATED";
export const ADD_WEEK_CLOSED = "ADD_WEEK_CLOSED";
export const ADD_WEEK_VELOCITY_CLOSED = "ADD_WEEK_VELOCITY_CLOSED";
export const ADD_WEEK_VELOCITY_CREATED = "ADD_WEEK_VELOCITY_CREATED";

export const ADD_COMPLETION_ESTIMATE = "ADD_COMPLETION_ESTIMATE";

export const ADD_FACET_STATE = "ADD_FACET_STATE";
export const ADD_FACET_AUTHOR = "ADD_FACET_STATE";
export const ADD_FACET_ASSIGNEE = "ADD_FACET_STATE";
export const ADD_FACET_ORGANIZATION = "ADD_FACET_STATE";
export const ADD_FACET_REPOSITORY = "ADD_FACET_STATE";
export const ADD_FACET_MILESTONE = "ADD_FACET_STATE";
export const ADD_FACET_MILESTONE_STATE = "ADD_FACET_STATE";
export const ADD_FACET_LABEL = "ADD_FACET_STATE";
