// src/js/constants/action-types.js
export const ADD_DAY = "ADD_DAY";
export const ADD_CLOSED_ISSUES_DAY = "ADD_CLOSED_ISSUES_DAY";
export const ADD_DAY_VELOCITY_CLOSED = "ADD_DAY_VELOCITY_CLOSED";
export const ADD_DAY_VELOCITY_CREATED = "ADD_DAY_VELOCITY_CREATED";

export const ADD_OPENED_ISSUES_WEEK = "ADD_OPENED_ISSUES_WEEK";
export const ADD_CLOSED_ISSUES_WEEK = "ADD_CLOSED_ISSUES_WEEK";
export const ADD_WEEK_VELOCITY_CLOSED = "ADD_WEEK_VELOCITY_CLOSED";
export const ADD_WEEK_VELOCITY_CREATED = "ADD_WEEK_VELOCITY_CREATED";