// src/js/constants/action-types.js
export const ADD_DAY_CREATED = "ADD_DAY_CREATED";
export const ADD_DAY_CLOSED = "ADD_DAY_CLOSED";
export const ADD_DAY_VELOCITY_CLOSED = "ADD_DAY_VELOCITY_CLOSED";
export const ADD_DAY_VELOCITY_CREATED = "ADD_DAY_VELOCITY_CREATED";

export const ADD_WEEK_CREATED = "ADD_WEEK_CREATED";
export const ADD_WEEK_CLOSED = "ADD_WEEK_CLOSED";
export const ADD_WEEK_VELOCITY_CLOSED = "ADD_WEEK_VELOCITY_CLOSED";
export const ADD_WEEK_VELOCITY_CREATED = "ADD_WEEK_VELOCITY_CREATED";

export const ADD_COMPLETION_ESTIMATE = "ADD_COMPLETION_ESTIMATE";